# Generated by Django 6.0.3 on 2026-03-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('students', '0003_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-week_start', 'day', 'title']},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.DateField(blank=True, help_text='The specific day this task is assigned to (within the week).', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('student', 'day', 'title')},
        ),
    ]
