# Generated by Django 6.0.3 on 2026-03-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_task_options_alter_task_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('personal', 'Personal'), ('extracurricular', 'Extracurricular'), ('health', 'Health'), ('other', 'Other')], default='academic', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
