# Generated by Django 6.0.3 on 2026-03-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(help_text='Unique roll number used for student identification and sorting', max_length=20, unique=True),
        ),
    ]
