# Generated by Django 6.0.3 on 2026-03-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name', 'section'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
