# Generated by Django 6.0.3 on 2026-03-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Excellence High School', max_length=255)),
                ('academic_year', models.CharField(default='2024 - 2025', max_length=50)),
                ('official_email', models.EmailField(default='admin@excellence.edu', max_length=254)),
                ('institution_address', models.TextField(default='123 Education Boulevard, Knowledge City')),
                ('enable_student_portal', models.BooleanField(default=True)),
                ('automated_email_notifications', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
