# Generated by Django 6.0.3 on 2026-03-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enforce_strong_passwords',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_absences',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_exam_results',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_fee_dues',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='session_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='theme_color',
            field=models.CharField(choices=[('indigo', 'Indigo / Primary'), ('sapphire', 'Sapphire Blue'), ('emerald', 'Emerald Green'), ('slate', 'Slate Dark')], default='indigo', max_length=20),
        ),
    ]
