# Generated by Django 6.0.3 on 2026-03-30 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='marks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='exam_name',
            field=models.CharField(default='Exam', help_text='e.g., Mid Term, Final Exam', max_length=100),
        ),
        migrations.AddField(
            model_name='marks',
            name='out_of',
            field=models.IntegerField(default=100, help_text='Maximum marks'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
