# Generated by Django 6.0.3 on 2026-03-17 14:30

from django.db import migrations, models
import django.core.validators
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(default='TCH', max_length=20, unique=True)),
                ('name', models.CharField(help_text="Teacher's full name", max_length=100)),
                ('email', models.EmailField(help_text='Unique email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='10-digit phone number', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be 10 digits', regex='^[0-9]{10}$')])),
                ('subject', models.CharField(help_text='Subject taught by teacher', max_length=100)),
                ('qualification', models.CharField(blank=True, help_text='Educational qualification', max_length=100)),
                ('experience_years', models.IntegerField(default=0, help_text='Years of teaching experience')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='teacher_email_idx'), models.Index(fields=['teacher_id'], name='teacher_id_idx')],
            },
        ),
    ]
