# Generated by Django 6.0.3 on 2026-03-24 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teacher',
            new_name='teachers_te_email_886f02_idx',
            old_name='teacher_email_idx',
        ),
        migrations.RenameIndex(
            model_name='teacher',
            new_name='teachers_te_teacher_5d8d41_idx',
            old_name='teacher_id_idx',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(help_text='10-digit phone number', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Phone must be 10 digits')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
