# Generated by Django 6.0.3 on 2026-03-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['time_slot__start_time', 'day_of_week'], 'verbose_name': 'Timetable Entry', 'verbose_name_plural': 'Timetable Entries'},
        ),
    ]
